In [3]:
# Tensorflow logistic regression
import numpy as np
import tensorflow as tf

tf.set_random_seed(0)  # 乱数シード

# weight, bias
w = tf.Variable(tf.zeros([2, 1]))
b = tf.Variable(tf.zeros([1]))

# model y = sigmmoid(w^T*x + b)
# input x
x = tf.placeholder(tf.float32, shape=[None, 2])
# teacher
t = tf.placeholder(tf.float32, shape=[None, 1])
# output y
y = tf.nn.sigmoid(tf.matmul(x, w) + b) 

cross_entropy = - tf.reduce_sum(t * tf.log(y) + (1 - t) * tf.log(1 - y))
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy)
# 確認
correct_prediction = tf.equal(tf.to_float(tf.greater(y, 0.5)), t)

# OR logic
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [1]])

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for epoch in range(200):
    sess.run(train_step, feed_dict={
            x: X,
            t: Y
        })

classified = correct_prediction.eval(session=sess, feed_dict={
        x: X,
        t: Y
    })
print(classified)

prob = y.eval(session=sess, feed_dict={
        x: X,
        t: Y
    })

print(prob)

# 学習したパラメータの確認
print('w:', sess.run(w))
print('b:', sess.run(b))

[[ True]
 [ True]
 [ True]
 [ True]]
[[ 0.22355038]
 [ 0.91425949]
 [ 0.91425949]
 [ 0.99747425]]
w: [[ 3.61188436]
 [ 3.61188436]]
b: [-1.24509501]


In [6]:
# Keras logistic regression
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

model = Sequential([
    Dense(input_dim=2, units=1),
    Activation('sigmoid')
])
model.compile(loss='binary_crossentropy', optimizer=SGD(lr=0.1))
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[1]])
model.fit(X,Y,epochs=200,batch_size=1)
classes = model.predict_classes(X, batch_size=1)
prob = model.predict_proba(X, batch_size=1)

print('classified')
print(Y == classes)
print()

print('output probability:')
print(prob)

Epoch 1/200
4/4 [==============================] - 0s - loss: 0.7670     
Epoch 2/200
4/4 [==============================] - 0s - loss: 0.6901     
Epoch 3/200
4/4 [==============================] - 0s - loss: 0.6319     
Epoch 4/200
4/4 [==============================] - 0s - loss: 0.5884     
Epoch 5/200
4/4 [==============================] - 0s - loss: 0.5546     
Epoch 6/200
4/4 [==============================] - 0s - loss: 0.5287     
Epoch 7/200
4/4 [==============================] - 0s - loss: 0.5073     
Epoch 8/200
4/4 [==============================] - 0s - loss: 0.4901     
Epoch 9/200
4/4 [==============================] - 0s - loss: 0.4750     
Epoch 10/200
4/4 [==============================] - 0s - loss: 0.4624     
Epoch 11/200
4/4 [==============================] - 0s - loss: 0.4520     
Epoch 12/200
4/4 [==============================] - 0s - loss: 0.4423     
Epoch 13/200
4/4 [==============================] - 0s - loss: 0.4338     
Epoch 14/200
4/4 [================

In [15]:
# Tensorflow Multi Logistic Regression
from sklearn.utils import shuffle

M = 2 # dimension of input
K = 3 # number of class
n = 100 # number of data per class
N = n * K # all data

# sample data
X1 = np.random.randn(n, M) + np.array([0, 10])
X2 = np.random.randn(n, M) + np.array([5, 5])
X3 = np.random.randn(n, M) + np.array([10, 0])
Y1 = np.array([[1,0,0] for _ in range(n)])
Y2 = np.array([[0,1,0] for _ in range(n)])
Y3 = np.array([[0,0,1] for _ in range(n)])

X = np.concatenate((X1, X2, X3), axis=0)
Y = np.concatenate((Y1, Y2, Y3), axis=0)

tf.set_random_seed(0)  # 乱数シード

# weight, bias
w = tf.Variable(tf.zeros([M, K]))
b = tf.Variable(tf.zeros([K]))

# model y = sigmmoid(w^T*x + b)
# input x
x = tf.placeholder(tf.float32, shape=[None, M])
# teacher
t = tf.placeholder(tf.float32, shape=[None, K])
# output y
y = tf.nn.softmax(tf.matmul(x, w) + b) 

cross_entropy = tf.reduce_mean(- tf.reduce_sum(t * tf.log(y), reduction_indices=[1]))
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy)
# 確認
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(t,1))

batch_size = 50
n_batches = N

for epoch in range(20):
    X_, Y_ = shuffle(X, Y)
    for i in range(n_batches):
        start = i * batch_size
        end = start + batch_size
        
        sess.run(train_step, feed_dict={
                x: X_[start:end],
                t: Y_[start:end]
            })
X_,Y_ = shuffle(X,Y)
classified = correct_prediction.eval(session=sess, feed_dict={
        x: X_[0:10],
        t: Y_[0:10]
    })
prob = y.eval(session=sess, feed_dict={
        x: X_[0:10]
    })

print('classified:')
print(classified)
print()
print('output probability:')
print(prob)

[[  2.50971248   9.19661696]
 [  1.82220356   9.75222107]
 [  0.07991778   8.45285846]
 [  0.08987834   9.11615396]
 [ -1.03512802   8.61007037]
 [  0.11630936   8.81385909]
 [  0.87108045   8.4030124 ]
 [  0.07484259   9.91415687]
 [ -1.247594    10.63337832]
 [ -0.34229866   9.78982612]
 [ -0.32555077  10.87783709]
 [ -1.345421     7.5379581 ]
 [  0.35244639   8.48805117]
 [  0.8690137    8.80057232]
 [  0.36401624   9.15561734]
 [ -0.90495458   8.57770864]
 [  0.6295849    9.88126663]
 [  0.74251925   9.85998861]
 [ -1.02300231  10.03993619]
 [  0.40124631   8.3205977 ]
 [  0.49784391   8.97865759]
 [  1.30625964   9.52853042]
 [  0.09290613  11.43560223]
 [  1.46110885  10.99403751]
 [  0.57596317  11.07512509]
 [ -0.55791066   8.47493259]
 [  0.96941338  10.05048336]
 [  0.59246057   9.24644572]
 [  0.33523857  10.64850264]
 [  0.06447264   9.96021033]
 [  0.98462697  10.9832528 ]
 [  1.35230703  10.42028087]
 [  0.06491236   9.82780887]
 [ -1.64368528  10.45532448]
 [  0.75497636

FailedPreconditionError: Attempting to use uninitialized value Variable_9
	 [[Node: Variable_9/read = Identity[T=DT_FLOAT, _class=["loc:@Variable_9"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_9)]]

Caused by op 'Variable_9/read', defined at:
  File "C:\Users\maeda\Anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\maeda\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Users\maeda\Anaconda3\lib\site-packages\traitlets\config\application.py", line 653, in launch_instance
    app.start()
  File "C:\Users\maeda\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\maeda\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\maeda\Anaconda3\lib\site-packages\tornado\ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\maeda\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\maeda\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-353671b96d2e>", line 32, in <module>
    b = tf.Variable(tf.zeros([K]))
  File "C:\Users\maeda\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 200, in __init__
    expected_shape=expected_shape)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 319, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "C:\Users\maeda\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1303, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\maeda\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Variable_9
	 [[Node: Variable_9/read = Identity[T=DT_FLOAT, _class=["loc:@Variable_9"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_9)]]


In [16]:
import numpy as np
import tensorflow as tf
from sklearn.utils import shuffle

np.random.seed(0)
tf.set_random_seed(0)

M = 2      # 入力データの次元
K = 3      # クラス数
n = 100    # クラスごとのデータ数
N = n * K  # 全データ数

'''
データの生成
'''
X1 = np.random.randn(n, M) + np.array([0, 10])
X2 = np.random.randn(n, M) + np.array([5, 5])
X3 = np.random.randn(n, M) + np.array([10, 0])
Y1 = np.array([[1, 0, 0] for i in range(n)])
Y2 = np.array([[0, 1, 0] for i in range(n)])
Y3 = np.array([[0, 0, 1] for i in range(n)])

X = np.concatenate((X1, X2, X3), axis=0)
Y = np.concatenate((Y1, Y2, Y3), axis=0)

'''
モデル設定
'''
W = tf.Variable(tf.zeros([M, K]))
b = tf.Variable(tf.zeros([K]))

x = tf.placeholder(tf.float32, shape=[None, M])
t = tf.placeholder(tf.float32, shape=[None, K])
y = tf.nn.softmax(tf.matmul(x, W) + b)

cross_entropy = tf.reduce_mean(-tf.reduce_sum(t * tf.log(y),
                               reduction_indices=[1]))
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy)

correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(t, 1))

'''
モデル学習
'''
# 初期化
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

batch_size = 50  # ミニバッチサイズ
n_batches = N // batch_size

# ミニバッチ学習
for epoch in range(20):
    X_, Y_ = shuffle(X, Y)

    for i in range(n_batches):
        start = i * batch_size
        end = start + batch_size

        sess.run(train_step, feed_dict={
            x: X_[start:end],
            t: Y_[start:end]
        })

'''
学習結果の確認
'''
X_, Y_ = shuffle(X, Y)

classified = correct_prediction.eval(session=sess, feed_dict={
    x: X_[0:10],
    t: Y_[0:10]
})
prob = y.eval(session=sess, feed_dict={
    x: X_[0:10]
})

print('classified:')
print(classified)
print()
print('output probability:')
print(prob)

classified:
[ True  True  True  True  True  True  True  True  True  True]

output probability:
[[  9.98682678e-01   1.31731527e-03   2.58784910e-10]
 [  3.43130948e-03   9.69049275e-01   2.75194254e-02]
 [  9.69157398e-01   3.08425445e-02   5.09097688e-08]
 [  1.93514787e-02   9.70684528e-01   9.96400509e-03]
 [  4.12158085e-09   8.59103166e-03   9.91409004e-01]
 [  1.71545204e-02   9.76335824e-01   6.50969939e-03]
 [  2.30860678e-07   4.24577259e-02   9.57542002e-01]
 [  7.25345686e-08   8.87839682e-03   9.91121531e-01]
 [  8.43027297e-12   1.41838231e-04   9.99858141e-01]
 [  9.95894194e-01   4.10580169e-03   2.68717937e-09]]
